name: HarshaLM CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Display Python Version
        run: python --version

      - name: Run Dataset Test
        run: python -m tests.test_dataset

      - name: Run Token Embedding Test
        run: python -m tests.embeddings.test_token_embedding
        
      - name: Run Position Embedding Test
        run: python -m tests.embeddings.test_positional_embedding

      - name: Run Scaled Dot Product Attention Test
        run: python -m tests.attention.test_scaled_dot_product

      - name: Run Multi Head Attention Test
        run: python -m tests.attention.test_multi_head_attention