name: HarshaLM CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/transformer

  pull_request:
    branches:
      - main
      - feature/transformer

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Main
        run: |
          python main.py

      - name: Test Dataset
        run: |
          python -m tests.test_dataset

      - name: Test Embedding
        run: |
          python -m tests.test_embedding

      - name: Test Position Embedding
        run: |
          python -m tests.test_position_embedding

      - name: Test Attention
        run: |
          python -m tests.test_attention
